// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBTHsX8Vv_LzFqqj3-GXej28YzzqRQ33Y',
    appId: '1:531236669326:web:9284516d70c9387c0486df',
    messagingSenderId: '531236669326',
    projectId: 'addis-movies',
    authDomain: 'addis-movies.firebaseapp.com',
    storageBucket: 'addis-movies.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmoQILq1eb7q96iFGaAd-45iGHXosCZ2s',
    appId: '1:531236669326:android:49e45c453d3892ea0486df',
    messagingSenderId: '531236669326',
    projectId: 'addis-movies',
    storageBucket: 'addis-movies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCudxh8bmDvEGKLRrhB14y_kNcKJVnKqO4',
    appId: '1:531236669326:ios:f4396b03d628bc730486df',
    messagingSenderId: '531236669326',
    projectId: 'addis-movies',
    storageBucket: 'addis-movies.firebasestorage.app',
    iosBundleId: 'com.addiscodr.addisMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCudxh8bmDvEGKLRrhB14y_kNcKJVnKqO4',
    appId: '1:531236669326:ios:f4396b03d628bc730486df',
    messagingSenderId: '531236669326',
    projectId: 'addis-movies',
    storageBucket: 'addis-movies.firebasestorage.app',
    iosBundleId: 'com.addiscodr.addisMovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBTHsX8Vv_LzFqqj3-GXej28YzzqRQ33Y',
    appId: '1:531236669326:web:3913940aaa9307c70486df',
    messagingSenderId: '531236669326',
    projectId: 'addis-movies',
    authDomain: 'addis-movies.firebaseapp.com',
    storageBucket: 'addis-movies.firebasestorage.app',
  );
}
